### PR TITLE
Add ruby-head compat

### PR DESCRIPTION
**Pull request by oriolgual**
ruby-head does not have the setup_arv method.  

We are using ruby-head because its new performance improvements.

### CODE REVIEW

**Comment by rmm5t** [comment]
+1 I currently have to use @oriolgual's fork to get spork-testunit working in Ruby 1.9.3-preview1.

**Comment by edison** [comment]
+1

**Comment by godfat** [comment]
Can we merge this?
This is required by Ruby 1.9.3, which was just released a few days ago.

**Comment by nixme** [comment]
Thanks... merging.

**Comment by semaperepelitsa** [comment]
Can we have a release with this fix? Thanks.

**Comment by nixme** [comment]
I'll cut a release this weekend.

**Comment by semaperepelitsa** [comment]
Any news on that? :-)

**Comment by rmm5t** [comment]
This is just a friendly reminder that we'd all love a bump to a new release.

**Comment by pkoch** [comment]
Not very pretty, but I solved this in my Gemfile with
`gem "spork-testunit", :git => "git://github.com/sporkrb/spork-testunit.git", :ref => "3e34c63e1c"`

**Comment by pkoch** [comment]
Ok, last comment didn't work out as expected with a clean gemset. Use gem `pkoch-spork-testunit` until these poor souls get around to releasing.

**Comment by nixme** [comment]
My sincere apologies. I'll push a new gem as soon as I get back to a computer.

**Comment by nixme** [comment]
Just pushed version 0.0.8.

**Pull request merged**
