### PR TITLE
spork-testunit not detected

### PR DESCRIPTION
**Pull request by justincase**
Spork only requires files in the `spork/test_framework/*.rb` subfolder. I moved the spork directory up one level and delete `/lib`.

Before with spork-testunit installed:

```
Usage: spork [test framework name] [options]

Options:
    -b, --bootstrap
    -d, --diagnose
    -h, --help
    -p, --port [PORT]

Supported test frameworks:
( ) Cucumber
( ) RSpec

Legend: ( ) - not detected in project   (*) - detected
```

After applying this patch:

```
Usage: spork [test framework name] [options]

Options:
    -b, --bootstrap
    -d, --diagnose
    -h, --help
    -p, --port [PORT]

Supported test frameworks:
( ) Cucumber
( ) RSpec
(*) TestUnit

Legend: ( ) - not detected in project   (*) - detected
```

### CODE REVIEW

**Comment by timcharper** [comment]
oh shoot, this is a problem on Spork's side, darnit.  They should be in lib.  I'll fix spork

**Comment by justincase** [comment]
Great, thanks!

**Comment by timcharper** [comment]
spork-0.9.0-rc9 contains the fix. Try out it and lemme know :)

**Comment by justincase** [comment]
Excellent, it's working! Thanks again.

**Pull request closed without merging**
